### ISSUE TITLE
Re-structure the repo and change name

### ISSUE THREAD

**Issue by dachafra** [kg-construct/rml-cc#34]
New structure:
- [x] folder `spec` with all the resources for the specification (the current content of the repo)*
- [x] folder `ontology`, which I think is coming from #31 
- [x] folder `shapes`, coming from #32 
- [x] folder `test-cases`, for #33 

Other changes:
- [x] The new name of the repo should be: `rml-cc`
- [x] *Remember that all specs need to be conformant with W3C: https://respec.org/docs/, an example could be https://kg-construct.github.io/rml-star/spec/docs/

**Comment by frmichel** [comment]
@chrdebru I'm starting to take this into account (including renaming the repo etc.)

**Comment by frmichel** [comment]
@dachafra can you please set me and Christophe as admins of the repo?

**Comment by frmichel** [comment]
Directory test-cases actually exists but is empty. Writing the tests is the object of issue #33, closing this one.
